In [617]:
import numpy as np
import jax
import jax.numpy as jnp
import optax
import pulp
import importlib
import matplotlib.pyplot as plt
import time

In [618]:
import J_sampler
import J_inference
import J_diagnostics

In [619]:
importlib.reload(J_inference)
importlib.reload(J_diagnostics)
importlib.reload(J_sampler)

<module 'J_sampler' from '/Users/lucaraffo/Desktop/final/J_sampler.py'>

In [620]:
n_spins = 10
n_samples = 1000

In [621]:
J = J_sampler.J_maker(n_spins)
h = jnp.diag(J)

In [622]:
samples = J_sampler.J_sampler(n_samples, J, h)

In [623]:
histogram = J_sampler._samples_to_histogram(samples)

In [624]:
J_hat, _ = J_inference.inverse_ising("RM", 0.001, "Y", histogram, n_steps = 50)

λ = 8.7183e-05  (reg = 0.001)
[1/10] reconstruction spin 0
0.25 [-0.01000001 -0.33391282  0.2950871  -0.12291279  0.00608718  0.04508717
 -0.3119127  -0.0009128   0.00108718 -0.01191282] 


0.23892201 [-0.00453639 -0.32011428  0.2822501  -0.11301029  0.00406834  0.04200589
 -0.30112636 -0.00141331 -0.00083019 -0.00897401] 


0.22849257 [ 0.00077629 -0.30568025  0.26928648 -0.10276948 -0.00111386  0.03788276
 -0.2895976  -0.0033945   0.00217247 -0.0048303 ] 


0.21871044 [ 0.00491422 -0.29074955  0.25559565 -0.09213229 -0.00300422  0.03455499
 -0.27772683 -0.0040417   0.00149234 -0.00172461] 


0.20953333 [ 6.8748561e-03 -2.7554083e-01  2.4140504e-01 -8.1227452e-02
 -2.1167607e-03  3.2383684e-02 -2.6574361e-01 -2.9627625e-03
 -1.4522921e-03 -1.0480192e-04] 


0.2009455 [ 0.00686455 -0.2602944   0.22717349 -0.07033063 -0.00138737  0.03057154
 -0.2537081  -0.00140183 -0.00304352  0.0008624 ] 


0.19293934 [ 5.5499570e-03 -2.4518888e-01  2.1315232e-01 -5.9640974e-02
 -1.6699152e-03  2.8733

In [625]:
J[0]

Array([ 0.        ,  0.804899  , -0.54303   , -0.32492518,  0.        ,
       -0.27853298,  0.78282833,  0.        ,  0.        ,  0.        ],      dtype=float32)

In [626]:
J_hat[0]

array([ 0.02028043,  0.3304429 , -0.31270725,  0.01625343,  0.02800277,
       -0.24572298,  0.3653439 , -0.01687074, -0.00356647,  0.03256203],
      dtype=float32)

In [627]:
J_hat2, _ = J_inference.inverse_ising("CSM", 0.001, "Y", histogram, n_steps = 100)

λ = 8.7183e-05  (reg = 0.001)
[1/10] reconstruction spin 0
-1.0 [-0.1600002  -5.3439126   4.720086   -1.9679126   0.09608722  0.720087
 -4.9919105  -0.01591257  0.01608709 -0.19191284] 


-1.1781284 [-0.09376436 -5.1692023   4.559872   -1.8422769   0.07574533  0.69090414
 -4.8621974  -0.01696916 -0.00664871 -0.15963694] 


-1.3502157 [-0.06169349 -5.064727    4.467396   -1.7674755   0.04885676  0.6824137
 -4.7964215  -0.01559435  0.00991629 -0.14254145] 


-1.5194232 [-5.6339614e-02 -5.0196419e+00  4.4282193e+00 -1.7335815e+00
  5.2102733e-02  7.0178437e-01 -4.7876592e+00  3.2347331e-03
  7.1044676e-03 -1.4986330e-01] 


-1.6885906 [-7.1982950e-02 -5.0319304e+00  4.4425054e+00 -1.7395362e+00
  6.9771618e-02  7.3835897e-01 -4.8294258e+00  2.7857322e-02
 -2.2229059e-04 -1.7102641e-01] 


-1.8607718 [-0.10508216 -5.1095743   4.519841   -1.7890084   0.09653211  0.7909588
 -4.9199715   0.05874083 -0.00862072 -0.20540951] 


-2.0394423 [-0.15347387 -5.2540126   4.6606154  -1.8766252   0.1425

In [628]:
J[0]

Array([ 0.        ,  0.804899  , -0.54303   , -0.32492518,  0.        ,
       -0.27853298,  0.78282833,  0.        ,  0.        ,  0.        ],      dtype=float32)

In [629]:
J_hat2[0]

array([-0.34347427,  1.4757503 , -0.6600097 , -0.789397  , -0.40757465,
       -0.16279344,  0.9916974 , -0.19360615,  0.05053747,  0.88570875],
      dtype=float32)