In [141]:
import numpy as np
import importlib
import jax
import jax.numpy as jnp
import math

import J_sampler
import J_inference
import J_diagnostics
import GGM_sampler
import GGM_inference
import GGM_diagnostics

In [146]:
importlib.reload(J_inference)
importlib.reload(J_sampler)
importlib.reload(J_diagnostics)

<module 'J_diagnostics' from '/Users/lucaraffo/Desktop/final/J_diagnostics.py'>

In [130]:
importlib.reload(GGM_inference)
importlib.reload(GGM_sampler)
importlib.reload(GGM_diagnostics)

<module 'GGM_diagnostics' from '/Users/lucaraffo/Desktop/final/GGM_diagnostics.py'>

In [148]:
n_spins = 5
n_samples = 10000

In [149]:
J = J_sampler.J_maker_01(n_spins)
h = jnp.diag(J)

In [150]:
samples = J_sampler.J_sampler_noise(n_samples, J, h)

In [151]:
J

Array([[0., 1., 1., 1., 0.],
       [1., 0., 1., 1., 0.],
       [1., 1., 0., 0., 0.],
       [1., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0.]], dtype=float32)

In [107]:
samples = GGM_sampler.precision_sampler_sign(J + 1.1 * jnp.eye(len(J[0])), n_samples)

In [152]:
samples

Array([[-1, -1, -1, -1, -1],
       [-1, -1, -1, -1, -1],
       [ 1,  1,  1, -1,  1],
       ...,
       [ 1,  1,  1, -1,  1],
       [-1, -1, -1, -1,  1],
       [-1, -1, -1,  1, -1]], dtype=int32)

In [153]:
histogram = J_sampler._samples_to_histogram(samples)

In [154]:
histogram

array([[2113,   -1,   -1,   -1,   -1,   -1],
       [   5,    1,   -1,   -1,   -1,   -1],
       [  41,   -1,    1,   -1,   -1,   -1],
       [   5,    1,    1,   -1,   -1,   -1],
       [  39,   -1,   -1,    1,   -1,   -1],
       [   9,    1,   -1,    1,   -1,   -1],
       [  34,   -1,    1,    1,   -1,   -1],
       [ 251,    1,    1,    1,   -1,   -1],
       [2082,   -1,   -1,   -1,    1,   -1],
       [   6,    1,   -1,   -1,    1,   -1],
       [  38,   -1,    1,   -1,    1,   -1],
       [   5,    1,    1,   -1,    1,   -1],
       [  41,   -1,   -1,    1,    1,   -1],
       [   4,    1,   -1,    1,    1,   -1],
       [  35,   -1,    1,    1,    1,   -1],
       [ 279,    1,    1,    1,    1,   -1],
       [ 282,   -1,   -1,   -1,   -1,    1],
       [  50,    1,   -1,   -1,   -1,    1],
       [   3,   -1,    1,   -1,   -1,    1],
       [  37,    1,    1,   -1,   -1,    1],
       [   8,   -1,   -1,    1,   -1,    1],
       [  39,    1,   -1,    1,   -1,    1],
       [  

In [155]:
J

Array([[0., 1., 1., 1., 0.],
       [1., 0., 1., 1., 0.],
       [1., 1., 0., 0., 0.],
       [1., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0.]], dtype=float32)

In [156]:
J_hat, _ = J_inference.inverse_ising("RISE", 0.1, "Y", histogram)

λ = 0.0024929  (reg = 0.1)
[1/5] reconstruction spin 0
[2/5] reconstruction spin 1
[3/5] reconstruction spin 2
[4/5] reconstruction spin 3
[5/5] reconstruction spin 4


In [158]:
J_hat

array([[ 3.9739780e-02,  9.6317559e-01,  9.4144428e-01,  5.6339004e-03,
         9.3378496e-01],
       [ 9.6317559e-01, -5.2865068e-03,  1.0024781e+00,  1.7158655e-02,
         6.9360062e-02],
       [ 9.4144428e-01,  1.0024781e+00, -2.0180767e-02, -9.6366471e-03,
         5.3485014e-02],
       [ 5.6339004e-03,  1.7158655e-02, -9.6366471e-03,  5.2438434e-03,
        -1.9071762e-04],
       [ 9.3378496e-01,  6.9360062e-02,  5.3485014e-02, -1.9071762e-04,
         2.1863272e-02]], dtype=float32)