In [338]:
import numpy as np
import jax
import jax.numpy as jnp
import optax
import pulp
import importlib
import matplotlib.pyplot as plt
import time as time

In [339]:
import GGM_sampler
import GGM_inference
import GGM_diagnostics
import J_sampler
import J_inference
import J_diagnostics

In [340]:
importlib.reload(GGM_inference)
importlib.reload(GGM_diagnostics)
importlib.reload(GGM_sampler)
importlib.reload(J_inference)
importlib.reload(J_diagnostics)
importlib.reload(J_sampler)

<module 'J_sampler' from '/Users/lucaraffo/Desktop/final/J_sampler.py'>

In [341]:
n_spins = 5
n_samples = 500

In [342]:
J_01 = J_sampler.J_maker_01(n_spins)
h = jnp.diag(J_01)

In [343]:
print(J_01)

[[0. 1. 1. 1. 0.]
 [1. 0. 1. 1. 0.]
 [1. 1. 0. 0. 0.]
 [1. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [344]:
samples = J_sampler.J_sampler_noise(n_samples, J_01, h, p = 0.1)

In [346]:
histogram = J_sampler._samples_to_histogram(samples)

In [ ]:
J_hat, histor = J_inference.inverse_ising("EMHT", 0.1, "Y", histogram, n_steps = 100)

SyntaxError: invalid syntax (930177988.py, line 1)